services:
  selenoid:
    image: aerokube/selenoid
    networks:
      - selenoid
    container_name: selenoid
    ports:
      - "4444:4444"
    environment:
      TZ: "America/Sao_Paulo"
    dns: 8.8.8.8
    volumes:
      - "./browsers/browsers.json:/etc/selenoid/browsers.json"
      - //var/run/docker.sock:/var/run/docker.sock
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "selenoid"]

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    networks:
      - selenoid
    ports:
      - "8080:8080"
    environment:
      TZ: "America/Sao_Paulo"
    dns: 8.8.8.8
    command: > 
      --selenoid-uri http://selenoid:4444 --allowed-origin *

    
networks:
  selenoid:
    external: true 